app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:8081"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

  kakao:
    api:
      base-url: https://dapi.kakao.com
      key: ${KAKAO_REST_API_KEY:}   # ← 환경변수에서 읽기(없으면 빈값)
  google:
    api-key: ${GOOGLE_API_KEY:}     # 구글 Places API 키
gemini:
  api-key: ${GEMINI_API_KEY:}       # Gemini API 키

management:
  endpoints:
    web:
      exposure:
        include: mappings,health