app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:8081"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

  kakao:
    api:
      base-url: https://dapi.kakao.com
      key: ${KAKAO_REST_API_KEY:}   # ← 환경변수에서 읽기(없으면 빈값)
