app:
  cors:
    # 로컬 개발에서 자주 쓰는 포트(React 3000, Vite 5173 등)
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:8081"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
