app:
  cors:
    # 실제 배포된 프론트 도메인으로 교체하세요 (예시는 한 개만 넣었지만, 쉼표로 여러 개 가능)
    allowed-origins: "https://myfrontend.com"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

#배포 시 반드시 실 도메인으로 바꿔주세요. (여러 개면 쉼표로 구분)