app:
  cors:
    # 실제 배포 도메인(여러 개면 쉼표로 추가)
    allowed-origins: "https://myfrontend.com"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  kakao:
    api:
      base-url: https://dapi.kakao.com
      key: ${KAKAO_REST_API_KEY:}   # 운영도 환경변수로
  google:
    api-key: ${GOOGLE_API_KEY:}     # 구글 Places API 키
gemini:
  api-key: ${GEMINI_API_KEY:}       # Gemini API 키

spring:
  datasource:
    # 운영에선 환경변수로 주입 권장
    url: ${DB_URL:jdbc:mysql://localhost:3306/ygup?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USER:ygup}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate        # 운영 권장(또는 none)
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

server:
  port: 8080
